# Generated by Django 4.2 on 2024-03-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("roll_number", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=25)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
