# Generated by Django 4.2 on 2024-03-11 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("studentmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mark",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
