# Generated by Django 4.2 on 2024-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentmanagement", "0002_student_mark_alter_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mark",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
