# Generated by Django 4.2 on 2024-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentmanagement", "0005_remove_student_is_active_studentattendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentattendance",
            name="leave_type",
            field=models.CharField(
                choices=[("half_day", "Half day"), ("full_day", "Full day")],
                default="half_day",
                max_length=20,
            ),
        ),
    ]
